apiVersion: v1
kind: Pod
metadata:
  labels:
    run: db1
  name: db1
spec:
  containers:
  - image: mysql
    name: db1
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: conf1
          key: pass  
       
